name = "MultiDeviceLinearAlgebra"
uuid = "32bb5913-70e1-44ea-8d43-6c4dc56badf2"
authors = ["Kyle Beggs (beggskw@gmail.com) and contributors"]
version = "0.0.1"

[compat]
julia = "1.10"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Test"]
